### ISSUE TITLE
Why didn't you compare your proposed approach with triplet loss ?

### ISSUE THREAD

**Issue by globallocal** [happynear/NormFace#22]
Dear Dr. Wang:
       I realized that you didn't compare your proposed loss with the state-of-art triplet loss. What' the reason? Thank you.

**Comment by happynear** [comment]
Because I can't get reasonable results using triplet loss, and I can't find source codes that can get reasonable results.

But you may refer to SphereFace paper (https://arxiv.org/pdf/1704.08063.pdf) to see the results of triplet loss. It's performance is similar with contrastive loss, much weaker than center loss.

**Comment by happynear** [comment]
As I mentioned in the introduction, metric learning algorithms (e.g. contrastive loss and triplet loss) has sampling problem. On large datasets used by face verification, it is almost impossible to enumerate all pairs or triplets of the datasets. We usually need hard mining algorithms to generate the pairs or triplets, which are tricky and difficult to implement.

**Comment by globallocal** [comment]
Thank you for your answer,  what you say makes sense.
